### ISSUE TITLE
gulpconfig.yml updates

### ISSUE THREAD

**Issue by illepic** [phase2/pattern-lab-starter#52]
`scssToJson` section currently indicates array of objects like this:

````yaml
scssToJson:
    - src: source/_patterns/00-base/01-colors/_color-vars.scss
      dest: source/_patterns/00-base/01-colors/colors.json
      lineStartsWith: $c-
      allowVarValues: false
    - src: source/_patterns/01-atoms/01-typography/fonts/_fonts.scss
      dest: source/_patterns/01-atoms/01-typography/fonts/font-sizes.json
      lineStartsWith: $fs--
      allowVarValues: false
````

when it should be formatted like this:

````yaml
scssToJson:
    -
      src: source/_patterns/00-base/01-colors/_color-vars.scss
      dest: source/_patterns/00-base/01-colors/colors.json
      lineStartsWith: $c-
      allowVarValues: true
    -
      src: source/_patterns/01-atoms/01-typography/fonts/_fonts.scss
      dest: source/_patterns/01-atoms/01-typography/fonts/font-sizes.json
      lineStartsWith: $fs--
      allowVarValues: false
````

Also, add `- ./bower_components` to `css.includePaths` array.
